### ISSUE TITLE
local variable 'has_error' referenced before assignment

### ISSUE THREAD

**Issue by Amirioelmos** [spotify/cstar#19]
hello
when run the cstar by this command :
 `cstar run --command "nodetool status" --host 192.168.1.1 --ssh-username amirio --ssh-password foobar`

receive this error :
Generating endpoint mapping
Traceback (most recent call last):
  File "/usr/local/bin/cstar", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/cstar/cstarcli.py", line 131, in main
    namespace.func(namespace)
  File "/usr/local/lib/python3.5/dist-packages/cstar/args.py", line 98, in <lambda>
    command_parser.set_defaults(func=lambda args: execute_command(args), command=command)
  File "/usr/local/lib/python3.5/dist-packages/cstar/cstarcli.py", line 115, in execute_command
    ssh_identity_file = args.ssh_identity_file)
  File "/usr/local/lib/python3.5/dist-packages/cstar/job.py", line 215, in setup
    endpoint_mapping = self.get_endpoint_mapping(current_topology)
  File "/usr/local/lib/python3.5/dist-packages/cstar/job.py", line 155, in get_endpoint_mapping
    if not has_error:
UnboundLocalError: local variable 'has_error' referenced before assignment

**Comment by Bj0rnen** [comment]
Does `nodetool cfstats | grep Keyspace` (on 192.168.1.1) output any keyspaces other than `"system"`? Can you paste the output of that command?

**Comment by Amirioelmos** [comment]
`$ nodetool cfstats | grep Keyspace
Keyspace : system_traces
Keyspace : system
Keyspace : system_distributed
Keyspace : filenames
Keyspace : system_schema
Keyspace : mome_backup
Keyspace : archive
Keyspace : prrp
Keyspace : foney
Keyspace : system_auth
`

**Comment by Bj0rnen** [comment]
Hi, sorry I took a while. I believe this will fix your issue: https://github.com/spotify/cstar/pull/20. May I ask which Cassandra version you are running, btw?

You can try this change right now with
```pip install git+ssh://git@github.com/spotify/cstar.git@FixKeyspaceParse```

If it works for you, then I'll merge the PR and release.

**Comment by Bj0rnen** [comment]
If you don't have ssh setup with github, you can use this instead
```pip install git+https://github.com/spotify/cstar.git@FixKeyspaceParse```

**Comment by adejanovski** [comment]
A workaround you can apply waiting for the fix to be merged is to specify the keyspace that has the largest replication factor with `--key-space <keyspace_name>`.

**Comment by Amirioelmos** [comment]
Thank you for answering
We first tried to change the code to solve the problem. And we did it.
We first assumed that there was a problem with our input. While we are still on this hypothesis.
We are currently using version 3.9 and 3.0.14.

**Comment by Amirioelmos** [comment]
I change this code and work correctly:
`def extract_keyspaces_from_cfstats(text):
    keyspace_names = []
    for line in str(text).split(":"):
        if not line.__contains__("Keyspace"):
            keyspace_names.append(line.replace(" ", ""))
    return keyspace_names`
