### ISSUE TITLE
Fails to get topology on locally authenticated nodes

### ISSUE THREAD

**Issue by hrast01** [spotify/cstar#33]
It appears that cstar can't get the topology of the ring when using local JMX authentication.

Command nodetool describecluster failed with status 1 on host 10.52.31.4
Command nodetool ring failed with status 1 on host 10.52.31.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cstar/cstarcli.py", line 116, in execute_command
    ssh_lib=args.ssh_lib)
  File "/usr/local/lib/python3.7/site-packages/cstar/job.py", line 203, in setup
    current_topology = current_topology | self.get_cluster_topology((seed,))
  File "/usr/local/lib/python3.7/site-packages/cstar/job.py", line 104, in get_cluster_topology
    ", ".join(tried_hosts))
cstar.exceptions.HostIsDown: ('Could not find any working host while fetching topology. Is Cassandra actually running? Tried the following hosts:', '10.52.31.4')
Error: ('Could not find any working host while fetching topology. Is Cassandra actually running? Tried the following hosts:', '10.52.31.4')

**Comment by adejanovski** [comment]
Hi @hrast01,

indeed cstar doesn't support this yet.
I'll try to give it a shot soon unless you want to contribute this improvement?

**Comment by hrast01** [comment]
I hadn't bothered to look at the code first (my bad).  I'll take a look and see if its beyond my meager skills, if I can fix it, I'll fork/PR.

**Comment by adejanovski** [comment]
Sounds good, let me know if you need some help.

**Comment by hrast01** [comment]
I've looked over the code, and its beyond my skills (and time) right now.

**Comment by adejanovski** [comment]
no worries, I'll give it a stab today.

**Comment by adejanovski** [comment]
fixed by #35
