### ISSUE TITLE
Cstar fails when trying to parse data coming from a Cassandra cluster hosted on an AWS Rack

### ISSUE THREAD

**Issue by RobinVerleun** [spotify/cstar#39]
When running Cstar, attempting to get node information from the tool causes an issue if the underlying nodetool call has incorrect formatting. The culprit is this line here:

https://github.com/spotify/cstar/blob/6ff4d90b2da215546a89bb4c70333e5ebe840add/cstar/nodetoolparser/simple.py#L33

An example of the output that can come from Cassandra which triggers this issue:

```

==========
Address         Rack        Status State   Load            Owns                Token
                                                                               
10.***.***.***  aws-us-east-1aUp     Normal  244.32 GB       12.53%            foobar
10.***.***.***  aws-us-east-1bUp     Normal  266.45 GB       12.50%            foobar
10.***.***.***  aws-us-east-1cUp     Normal  276.46 GB       12.47%            foobar

```

The parsing fails and only counts seven words in the row, not eight. Would be nice if this had some flexibility to handle this edge case.

**Comment by adejanovski** [comment]
I'm currently removing the reliance on `nodetool ring` in favor of `nodetool status` which shouldn't have that issue.

I'll be merged and released soon.

**Comment by parham-pythian** [comment]
Thank you, @adejanovski . We are also having a current issue with `nodetool ring` -- will it be completely removed from the run?

**Comment by adejanovski** [comment]
Yes, we actually don't need it.
`nodetool status` gives us the list of hosts in the cluster and we use `nodetool describering` to map the tokens to their replicas.
The PR will also cache the endpoint mapping we generate from describering in order to speed things up: #41
