### ISSUE TITLE
cstar fails on getting topology

### ISSUE THREAD

**Issue by sigalits** [spotify/cstar#64]
Hi
I am trying to use cstar from jumping host ; installed  cstar version 0.8.0
first try to connect with seed-host i get this message :
sigaliths@packer:/home/sigaliths/awsDba >cstar run --command='df -hP' --seed-host 10.162.XX.XX --ssh-username=ec2-user --ssh-identity-file=../my_file -v                                          
Job id is cd4ff9f9-711b-43a1-814d-f9610ecd479c
Running /usr/lib/python3.6/site-packages/cstar/resources/commands/run.sh
Starting setup
Strategy: topology
Cluster parallel: True
DC parallel: False
Loading cluster topology
Command nodetool describecluster failed with status 127 on host 10.162.XX.XX
Command nodetool status failed with status 127 on host 10.162.XX.XX
Traceback (most recent call last):
  File "/usr/bin/cstar", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/cstar/cstarcli.py", line 214, in main
    namespace.func(namespace)
  File "/usr/lib/python3.6/site-packages/cstar/args.py", line 117, in <lambda>
    command_parser.set_defaults(func=lambda args: execute_command(args), command=command)
  File "/usr/lib/python3.6/site-packages/cstar/cstarcli.py", line 132, in execute_command
    resolve_hostnames=args.resolve_hostnames)
  File "/usr/lib/python3.6/site-packages/cstar/job.py", line 269, in setup
    current_topology = current_topology | self.get_cluster_topology(seeds)
  File "/usr/lib/python3.6/site-packages/cstar/job.py", line 126, in get_cluster_topology
    ", ".join([x.ip for x in tried_hosts]))
  File "/usr/lib/python3.6/site-packages/cstar/job.py", line 126, in <listcomp>
    ", ".join([x.ip for x in tried_hosts]))
AttributeError: 'str' object has no attribute 'ip'

ip address is available , and connection to the server with the ssh key is working.
running nodetool status locally on that machine also scucceeds.
what am i missing?
shouldt it connect by ssh to the server to retrieve the nodetool status output? it doing it remotely?

**Comment by sigalits** [comment]
could it be related to  issue #39
of @parham-pythian and @RobinVerleun ?
The JMX port is open and ssh to the server with the supplied key is working.

this message **"AttributeError: 'str' object has no attribute 'ip'" ,** might be suggesting parsing issue?
would appreciate any help here.
Thanks you very much

**Comment by caiopavanelli** [comment]
Hello! I ran into the same issue and what worked for me was to prepend `export PATH=/opt/cassandra/bin:$PATH` to `/etc/bash.bashrc`. Found that here https://github.com/spotify/cstar/blob/6172580a3ceba091f9599df355c267f9ce22a99a/tests/integration-cassandra.docker#L23
